# Generated by Django 4.1.4 on 2022-12-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, upload_to="portfolio/images/"),
        ),
        migrations.AlterField(
            model_name="blog", name="title", field=models.CharField(max_length=50),
        ),
    ]
