# Generated by Django 4.1.4 on 2022-12-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_image_alter_blog_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="image",),
    ]
